FROM node:lts-alpine as build

ARG REACT_APP_RM_API
ARG REACT_APP_TMDB_API
ARG REACT_APP_TMDB_TOKEN

ENV VITE_RM_API=${REACT_APP_RM_API}
ENV VITE_TMDB_API=${REACT_APP_TMDB_API}
ENV VITE_TMDB_TOKEN=${REACT_APP_TMDB_TOKEN}

WORKDIR /app
COPY . /app
RUN npm install
RUN npm run build

FROM nginx
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
